update dotfile

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
+# Reference: https://github.com/nickjj/dotfiles/blob/master/install
 
-set -e
+# set -e
 
 os_type="$(uname -s)"
 
@@ -35,17 +36,24 @@ esac
 ###############################################################################
 # Create initial directories
 ###############################################################################
-
 mkdir -p "${HOME}/.config/zsh" "${HOME}/.cache/zsh" \
     "${HOME}/.local/bin" "${HOME}/.local/share" \
     "${HOME}/.local/state" "${HOME}/.vim/spell"
 
 ###############################################################################
+# Install Plug (Vim plugin manager)
+###############################################################################
+curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
+  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+
+
+###############################################################################
 # Install oh-my-zsh
 ###############################################################################
-OH_MY_ZSH_PATH="${HOME}/.oh-my-zsh"
-ZSH_CUSTOM_SYNTAX=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
-ZSH_CUSTOM_AUTOSUG=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
+OH_MY_ZSH_PATH="${HOME}/.config/zsh/ohmyzsh/"
+ZSH_CUSTOM="${HOME}/.config/zsh/ohmyzsh/custom"
+ZSH_CUSTOM_SYNTAX="${HOME}/.config/zsh/ohmyzsh/custom/pluginszsh-syntax-highlighting"
+ZSH_CUSTOM_AUTOSUG="${HOME}/.config/zsh/ohmyzsh/custom/pluginscustom/plugins/zsh-autosuggestions"
 
 # install oh-my-zsh
 if ! [ -d "$OH_MY_ZSH_PATH" ]; then
@@ -57,26 +65,20 @@ fi
 
 # install syntax-highlighting
 if ! [ -d "$ZSH_CUSTOM_SYNTAX" ]; then
-    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
+    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting
 fi
 
 # install auto-suggestions
-if ! [ -d "$ZSH_CUSTOM_SYNTAX" ]; then
+if ! [ -d "$ZSH_CUSTOM_AUTOSUG" ]; then
     git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
 fi
 
 # install autojump
 sudo -E apt-get install autojump
 
-
-
 ###############################################################################
-# Install Plug (Vim plugin manager)
+# Setup symlink
 ###############################################################################
-
-curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
-  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
-
 cat << EOF
 
 A potentially dangerous action is about to happen. The above files are going to
@@ -89,18 +91,6 @@ overwritten with the files that come with my dotfiles (left side).
 
 If you care about your original config files now would be the time to back
 them up. They will ALL be overwritten if you say yes to the prompt below.
-EOF
-
-while true; do
-  read -rep $'\nReady to continue and apply the symlinks? (y) ' y
-  case "${y}" in
-      [Yy]*)
-
-          break;;
-      *) echo "Please answer y or CTRL+c the script to abort everything";;
-  esac
-done
-
 
 ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv"
 ln -fs "${clone_path}/.tmux.conf" "${HOME}/.tmux.conf"
@@ -109,6 +99,26 @@ ln -fs "${clone_path}/.vim/spell/en.utf-8.add" "${HOME}/.vim/spell/en.utf-8.add"
 ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc"
 ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile"
 ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases"
+EOF
+
+while true; do
+  read -rep $'\nReady to continue and apply the symlinks? (y/n/ctrl+c) ' y
+  case "${y}" in
+      [Yy]*)
+        ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv"
+        ln -fs "${clone_path}/.tmux.conf" "${HOME}/.tmux.conf"
+        ln -fs "${clone_path}/.vimrc" "${HOME}/.vimrc"
+        ln -fs "${clone_path}/.vim/spell/en.utf-8.add" "${HOME}/.vim/spell/en.utf-8.add"
+        ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc"
+        ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile"
+        ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases"
+        break;;
+      [Nn]*)
+        echo "do not create symbolic link"
+        break;;
+      *) echo "Please answer y or CTRL+c the script to abort everything";;
+  esac
+done
 
 ###############################################################################
 # Install Vim plugins
@@ -133,15 +143,20 @@ else
 fi
 
 ###############################################################################
+# Set conda base environment
+###############################################################################
+command -v conda env create -f environental.yml >/dev/null 2>&1
+if [ $? -eq 0 ]; then
+    echo "Environmental installed"
+else 
+    conda env create -f environment.yml
+fi
+
+###############################################################################
 # Done!
 ###############################################################################
-
 cat << EOF
 Everything was installed successfully!
-
-Check out the README file on GitHub to do 1 quick thing manually:
-
-https://github.com/nickjj/dotfiles#did-you-install-everything-successfully
 
 You can safely close this terminal.
 
